#ifndef HARDWAREDEF_SENSORBOARD_H
#define HARDWAREDEF_SENSORBOARD_H

#define PD6_LED   6
#define PB0_POWERMETER1 8
#define PB1_POWERMETER2 9
#define PB2_POWERMETER3 10
#define PD7_RESET_POWERMETERS 7

#endif
